In [2]:
import pandas as pd
data = {
 'Order_ID': ['1001', '1002', '1003', '1004', '1005'],
 'Product_ID': ['P101', 'P102', 'P103', 'P101', 'P104'],
 'Product_Name': ['Laptop', 'Smartphone', 'Headphones', 'Laptop',
'Coffee Maker'],
 'Category': ['Electronics', 'Electronics', 'Accessories',
'Electronics', 'Kitchen'],
 'Quantity': [2, 1, 5, 3, 2],
 'Amount': [1600, 600, 500, 2400, 100],
 'Date': ['2024-01-10', '2024-01-11', '2024-01-12', '2024-01-12',
'2024-01-13'],
 'Region': ['North', 'South', 'East', 'West', 'North'],
}

filtered=pd.DataFrame(data)
filtered

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North

In [3]:
print("Fitering :- is the process of selecting specific aount of data from the given dataset")

Fitering :- is the process of selecting specific aount of data from the given dataset

In [11]:
print("To filter only sales related to Electronics products")
Category=filtered[filtered["Category"]=="Electronics"]
Category

To filter only sales related to Electronics products

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West

In [10]:
print(" To filter sales that are greater than 1,000")
Sales=filtered[filtered["Amount"]>1000]
Sales

 To filter sales that are greater than 1,000

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West

In [20]:
print("Filtered by Total Amount (>1000) AND Date (Before Jan 12, 2024)")
filtered["Date"]=pd.to_datetime(filtered["Date"])
Filter=filtered[(filtered["Amount"]>1000) & (filtered["Date"]<'2024-01-12')]
Filter

Filtered by Total Amount (>1000) AND Date (Before Jan 12, 2024)

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North