In [1]:
import pandas as pd
import numpy as np

students = pd.DataFrame({
    "student_id": [101,102,103,104,105,106,107,108,108],
    "name": [
        "  Abel ",
        "Hana",
        "Mekdes",
        "Solomon",
        None,
        "dawit",
        "Sara ",
        "Yonas",
        "Yonas"
    ],
    "age": [
        21,
        22,
        np.nan,
        25,
        20,
        "twenty one",
        23,
        200,
        200
    ],
    "department": [
        "Computer Science",
        "computer science",
        "IT",
        "Information Technology",
        "CS",
        "cs",
        "Software Engineering",
        "SE",
        "SE"
    ],
    "gpa": [
        3.5,
        3.8,
        3.2,
        np.nan,
        4.9,
        3.6,
        3.7,
        2.9,
        2.9
    ],
    "scholarship": [
        "Yes",
        "No",
        "yes",
        "YES",
        None,
        "no",
        "Yes",
        "No",
        "No"
    ]
})
print(students)

   student_id     name         age              department  gpa scholarship
0         101    Abel           21        Computer Science  3.5         Yes
1         102     Hana          22        computer science  3.8          No
2         103   Mekdes         NaN                      IT  3.2         yes
3         104  Solomon          25  Information Technology  NaN         YES
4         105     None          20                      CS  4.9        None
5         106    dawit  twenty one                      cs  3.6          no
6         107    Sara           23    Software Engineering  3.7         Yes
7         108    Yonas         200                      SE  2.9          No
8         108    Yonas         200                      SE  2.9          No

In [2]:
students.fillna("🚩")

   student_id     name         age              department  gpa scholarship
0         101    Abel           21        Computer Science  3.5         Yes
1         102     Hana          22        computer science  3.8          No
2         103   Mekdes           🚩                      IT  3.2         yes
3         104  Solomon          25  Information Technology    🚩         YES
4         105        🚩          20                      CS  4.9           🚩
5         106    dawit  twenty one                      cs  3.6          no
6         107    Sara           23    Software Engineering  3.7         Yes
7         108    Yonas         200                      SE  2.9          No
8         108    Yonas         200                      SE  2.9          No

In [3]:
students["name"]=students["name"].str.strip().fillna("Unkoun_Name")
print(students["name"])

0           Abel
1           Hana
2         Mekdes
3        Solomon
4    Unkoun_Name
5          dawit
6           Sara
7          Yonas
8          Yonas
Name: name, dtype: object

In [4]:
students["age"] = pd.to_numeric(students["age"], errors="coerce")
print(students["age"])

0     21.0
1     22.0
2      NaN
3     25.0
4     20.0
5      NaN
6     23.0
7    200.0
8    200.0
Name: age, dtype: float64

In [5]:
students["age"] = students["age"].replace({
    200:20
})

In [6]:
print(students["age"])

0    21.0
1    22.0
2     NaN
3    25.0
4    20.0
5     NaN
6    23.0
7    20.0
8    20.0
Name: age, dtype: float64

In [7]:
students["age"]=students["age"].fillna(students["age"].mean())
students["age"]=students["age"].astype(int)
print(students["age"])

0    21
1    22
2    21
3    25
4    20
5    21
6    23
7    20
8    20
Name: age, dtype: int64

In [8]:
print(students)

   student_id         name  age              department  gpa scholarship
0         101         Abel   21        Computer Science  3.5         Yes
1         102         Hana   22        computer science  3.8          No
2         103       Mekdes   21                      IT  3.2         yes
3         104      Solomon   25  Information Technology  NaN         YES
4         105  Unkoun_Name   20                      CS  4.9        None
5         106        dawit   21                      cs  3.6          no
6         107         Sara   23    Software Engineering  3.7         Yes
7         108        Yonas   20                      SE  2.9          No
8         108        Yonas   20                      SE  2.9          No

In [9]:
students["department"]=students["department"].replace({
    "Computer Science":"CS",
    "computer science":"CS",
    "Information Technology":"IT",
    "cs":"CS",
    "Software Engineering":"SE"
    
    
})

In [10]:
print(students["department"])

0    CS
1    CS
2    IT
3    IT
4    CS
5    CS
6    SE
7    SE
8    SE
Name: department, dtype: object

In [11]:
students["scholarship"].fillna(students["scholarship"].mode()[0])
students["scholarship"].str.title()
print(students["scholarship"])

0     Yes
1      No
2     yes
3     YES
4    None
5      no
6     Yes
7      No
8      No
Name: scholarship, dtype: object

In [12]:
students["scholarship"]=students["scholarship"].replace(
    {
        "YES":"Yes",
        "yes":"Yes",
        "no":"No"
        
    }
)
print(students["scholarship"])

0     Yes
1      No
2     Yes
3     Yes
4    None
5      No
6     Yes
7      No
8      No
Name: scholarship, dtype: object

In [13]:
students["age"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: age, dtype: bool

In [14]:
students[students["gpa"] > 4]

   student_id         name  age department  gpa scholarship
4         105  Unkoun_Name   20         CS  4.9        None

In [15]:
students.loc[
    students["gpa"] > 4,
    "gpa"
] = np.nan

In [16]:
print(students["gpa"])

0    3.5
1    3.8
2    3.2
3    NaN
4    NaN
5    3.6
6    3.7
7    2.9
8    2.9
Name: gpa, dtype: float64

In [17]:
students["gpa"]=students["gpa"].fillna(students["gpa"].mean())

In [18]:
print(students["gpa"])

0    3.500000
1    3.800000
2    3.200000
3    3.371429
4    3.371429
5    3.600000
6    3.700000
7    2.900000
8    2.900000
Name: gpa, dtype: float64

In [19]:
print(students)

   student_id         name  age department       gpa scholarship
0         101         Abel   21         CS  3.500000         Yes
1         102         Hana   22         CS  3.800000          No
2         103       Mekdes   21         IT  3.200000         Yes
3         104      Solomon   25         IT  3.371429         Yes
4         105  Unkoun_Name   20         CS  3.371429        None
5         106        dawit   21         CS  3.600000          No
6         107         Sara   23         SE  3.700000         Yes
7         108        Yonas   20         SE  2.900000          No
8         108        Yonas   20         SE  2.900000          No

In [20]:
students["scholarship"]=students["scholarship"].fillna(students["scholarship"].mode()[0])

In [21]:
print(students["scholarship"])

0    Yes
1     No
2    Yes
3    Yes
4     No
5     No
6    Yes
7     No
8     No
Name: scholarship, dtype: object

In [22]:
print(students)

   student_id         name  age department       gpa scholarship
0         101         Abel   21         CS  3.500000         Yes
1         102         Hana   22         CS  3.800000          No
2         103       Mekdes   21         IT  3.200000         Yes
3         104      Solomon   25         IT  3.371429         Yes
4         105  Unkoun_Name   20         CS  3.371429          No
5         106        dawit   21         CS  3.600000          No
6         107         Sara   23         SE  3.700000         Yes
7         108        Yonas   20         SE  2.900000          No
8         108        Yonas   20         SE  2.900000          No