In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
students=pd.DataFrame({
    "name": ["Abel", "Hana", "Abel", None],
    "age": [21, np.nan, 21, 23],
    "department": ["CS", "IT", "CS", "SE"],
    "gpa": [3.5, 3.8, 3.5, np.nan]
    
})

In [4]:
print(students)

   name   age department  gpa
0  Abel  21.0         CS  3.5
1  Hana   NaN         IT  3.8
2  Abel  21.0         CS  3.5
3  None  23.0         SE  NaN

In [5]:
students.isnull()

    name    age  department    gpa
0  False  False       False  False
1  False   True       False  False
2  False  False       False  False
3   True  False       False   True

In [6]:
students.fillna("🚩 ")

   name   age department  gpa
0  Abel  21.0         CS  3.5
1  Hana    🚩          IT  3.8
2  Abel  21.0         CS  3.5
3    🚩   23.0         SE   🚩

In [7]:
students["name"]=students["name"].fillna("Unkown")
print(students["name"])

0      Abel
1      Hana
2      Abel
3    Unkown
Name: name, dtype: object

In [8]:
students["age"]=students["age"].fillna(students["age"].mode()[0])
print(students)

     name   age department  gpa
0    Abel  21.0         CS  3.5
1    Hana  21.0         IT  3.8
2    Abel  21.0         CS  3.5
3  Unkown  23.0         SE  NaN

In [9]:
students["gpa"]=students["gpa"].fillna(students["gpa"].mean())
print(students["gpa"])

0    3.5
1    3.8
2    3.5
3    3.6
Name: gpa, dtype: float64

In [10]:
print("the output for cleaned data")
print(students)

the output for cleaned data
     name   age department  gpa
0    Abel  21.0         CS  3.5
1    Hana  21.0         IT  3.8
2    Abel  21.0         CS  3.5
3  Unkown  23.0         SE  3.6