In [3]:
# Dataset 1: Customers
import pandas as pd
customers = pd.DataFrame({
"Customer_ID": ["C001", "C002", "C003", "C004", "C005", "C006"],
"Customer_Name": ["Abel", "Sara", "John", "Helen", "Samuel","David"],
"City": ["Addis Ababa", "Adama", "Jimma", "Bahir Dar", "Hawassa","Dire Dawa"]
})
customers

  Customer_ID Customer_Name         City
0        C001          Abel  Addis Ababa
1        C002          Sara        Adama
2        C003          John        Jimma
3        C004         Helen    Bahir Dar
4        C005        Samuel      Hawassa
5        C006         David    Dire Dawa

In [4]:
# Dataset 2: Orders
orders = pd.DataFrame({
"Order_ID": [101,102,103,104,105,106,107],
"Customer_ID": ["C001","C002","C001","C004","C007","C006","C006"],"Product":
["Laptop","Phone","Mouse","Keyboard","Tablet","Monitor","Printer"],"Amount": [1200,800,45,150,650,700,300]
})
orders

   Order_ID Customer_ID   Product  Amount
0       101        C001    Laptop    1200
1       102        C002     Phone     800
2       103        C001     Mouse      45
3       104        C004  Keyboard     150
4       105        C007    Tablet     650
5       106        C006   Monitor     700
6       107        C006   Printer     300

In [9]:
# Exercise 1 — Customer Purchase Report
# The sales manager wants a report that contains only valid purchases made by registeredcustomers.
# Create a report showing:
# Customer Name,City,Product,Amount
# Questions
# 1. How many records are returned?
# Total record returnd=6
# 2. Which order is excluded from the report?
# Order_ID = 105,
# 3. Why was that order excluded?
# It belongs to Customer_ID = C007,But C007 is NOT in customers table
report=pd.merge(customers,orders,on="Customer_ID" , how="inner")
report = report[["Customer_Name", "City", "Product", "Amount"]]
report

  Customer_Name         City   Product  Amount
0          Abel  Addis Ababa    Laptop    1200
1          Abel  Addis Ababa     Mouse      45
2          Sara        Adama     Phone     800
3         Helen    Bahir Dar  Keyboard     150
4         David    Dire Dawa   Monitor     700
5         David    Dire Dawa   Printer     300

  Customer_Name         City   Product  Amount
0          Abel  Addis Ababa    Laptop  1200.0
1          Abel  Addis Ababa     Mouse    45.0
2          Sara        Adama     Phone   800.0
3          John        Jimma       NaN     NaN
4         Helen    Bahir Dar  Keyboard   150.0
5        Samuel      Hawassa       NaN     NaN
6         David    Dire Dawa   Monitor   700.0
7         David    Dire Dawa   Printer   300.0

In [10]:
# Exercise 5 — Customer Support Investigation
# Customer David contacts customer support claiming he has placed several orders.
# Generate a report showing:
# Customer Name
# Product
# Amount
# Questions
df = pd.merge(customers, orders, on="Customer_ID", how="inner")
david = df[df["Customer_Name"] == "David"]
david

  Customer_ID Customer_Name       City  Order_ID  Product  Amount
4        C006         David  Dire Dawa       106  Monitor     700
5        C006         David  Dire Dawa       107  Printer     300

In [ ]:
# # 1. How many orders has David placed?
# David has placed 2 orders.
    # Monitor
    # Printer

In [ ]:
# 2. What is his total spending?
    # 700 + 300 = 1000

In [ ]:
# # 3. Would this report include customers who have never placed
# orders? Explain your answer.
    # No.
    # This report uses an INNER JOIN, which returns only the
    # records that have matching Customer_ID values in both 
    # the Customers and Orders tables.