In [2]:
# Dataset 1: Customers
import pandas as pd
customers = pd.DataFrame({
"Customer_ID": ["C001", "C002", "C003", "C004", "C005", "C006"],
"Customer_Name": ["Abel", "Sara", "John", "Helen", "Samuel","David"],
"City": ["Addis Ababa", "Adama", "Jimma", "Bahir Dar", "Hawassa","Dire Dawa"]
})
customers

  Customer_ID Customer_Name         City
0        C001          Abel  Addis Ababa
1        C002          Sara        Adama
2        C003          John        Jimma
3        C004         Helen    Bahir Dar
4        C005        Samuel      Hawassa
5        C006         David    Dire Dawa

In [3]:
# Dataset 2: Orders
orders = pd.DataFrame({
"Order_ID": [101,102,103,104,105,106,107],
"Customer_ID": ["C001","C002","C001","C004","C007","C006","C006"],"Product":
["Laptop","Phone","Mouse","Keyboard","Tablet","Monitor","Printer"],"Amount": [1200,800,45,150,650,700,300]
})
orders

   Order_ID Customer_ID   Product  Amount
0       101        C001    Laptop    1200
1       102        C002     Phone     800
2       103        C001     Mouse      45
3       104        C004  Keyboard     150
4       105        C007    Tablet     650
5       106        C006   Monitor     700
6       107        C006   Printer     300

In [4]:
# Exercise 2 — Order Investigation
# The finance department wants to review every order, even if customer information is
# unavailable.
# Create a report showing:
# Order ID
# Customer ID
# Customer Name
# Product
# Amount
# Questions
# 1. Which order has missing customer information?
# order_Id=105
# 2. Why is the customer information missing?
# Orders table has C007
# But customers table does NOT contain C007
# So join cannot find matching row
# 3. How many registered customers do not appear in this report?
# Answer: 0 customers
report2 = pd.merge(customers, orders, on="Customer_ID", how="right")
report2 = report2[["Order_ID","Customer_ID","Customer_Name","Product","Amount"]]
report2

   Order_ID Customer_ID Customer_Name   Product  Amount
0       101        C001          Abel    Laptop    1200
1       102        C002          Sara     Phone     800
2       103        C001          Abel     Mouse      45
3       104        C004         Helen  Keyboard     150
4       105        C007           NaN    Tablet     650
5       106        C006         David   Monitor     700
6       107        C006         David   Printer     300