In [3]:
import pandas as pd
data = {
 'Order_ID': ['1001', '1002', '1003', '1004', '1005'],
 'Product_ID': ['P101', 'P102', 'P103', 'P101', 'P104'],
 'Product_Name': ['Laptop', 'Smartphone', 'Headphones', 'Laptop',
'Coffee Maker'],
 'Category': ['Electronics', 'Electronics', 'Accessories',
'Electronics', 'Kitchen'],
 'Quantity': [2, 1, 5, 3, 2],
 'Amount': [1600, 600, 500, 2400, 100],
 'Date': ['2024-01-10', '2024-01-11', '2024-01-12', '2024-01-12',
'2024-01-13'],
 'Region': ['North', 'South', 'East', 'West', 'North'],
}
df_sales=pd.DataFrame(data)
df_sales

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East
3,1004,P101,Laptop,Electronics,3,2400,2024-01-12,West
4,1005,P104,Coffee Maker,Kitchen,2,100,2024-01-13,North

In [4]:
print("Subsetting ማለት ከdataset ውስጥ የሚያስፈልጉትን rows, columns, ወይም ሁለቱንም መምረጥ ነው።")

Subsetting ማለት ከdataset ውስጥ የሚያስፈልጉትን rows, columns, ወይም ሁለቱንም መምረጥ ነው።

In [10]:
# Subsetting only Order_ID,product_name and amount
subset_df = df_sales[['Order_ID', 'Product_Name', 'Amount']]
subset_df

  Order_ID  Product_Name  Amount
0     1001        Laptop    1600
1     1002    Smartphone     600
2     1003    Headphones     500
3     1004        Laptop    2400
4     1005  Coffee Maker     100

In [12]:
print("We can use iloc function(method) to filter rows in subsetting")
Row=df_sales.iloc[:3]
Row

We can use iloc function(method) to filter rows in subsetting

,Order_ID,Product_ID,Product_Name,Category,Quantity,Amount,Date,Region
0,1001,P101,Laptop,Electronics,2,1600,2024-01-10,North
1,1002,P102,Smartphone,Electronics,1,600,2024-01-11,South
2,1003,P103,Headphones,Accessories,5,500,2024-01-12,East

In [13]:
print("Selecting Rows and Columns Together")

Selecting Rows and Columns Together

In [16]:
Row_Col=df_sales.loc[df_sales["Amount"]>1000,["Order_ID","Product_ID","Product_Name","Amount"]]
Row_Col

  Order_ID Product_ID Product_Name  Amount
0     1001       P101       Laptop    1600
3     1004       P101       Laptop    2400