In [3]:
# Load the pandas package and create the dataset
import pandas as pd
data = {
 'Student_ID': ['S001', 'S002', 'S003', 'S004', 'S005'],
 'Mathematics' : [85, 75, 95, 65, 90],
 'Science' : [78, 88, 82, 85, 79],
 'English' : [90, 85, 80, 70, 95],
 'IT' : [89, 65, 88, 92, 98]
}
df_result = pd.DataFrame(data)
df_result

  Student_ID  Mathematics  Science  English  IT
0       S001           85       78       90  89
1       S002           75       88       85  65
2       S003           95       82       80  88
3       S004           65       85       70  92
4       S005           90       79       95  98

In [4]:
import numpy as np
df_result['Average'] = np.mean(df_result[['Mathematics', 'Science','English', 'IT']], axis=1)
# df_result

  Student_ID  Mathematics  Science  English  IT  Average
0       S001           85       78       90  89    85.50
1       S002           75       88       85  65    78.25
2       S003           95       82       80  88    86.25
3       S004           65       85       70  92    78.00
4       S005           90       79       95  98    90.50

In [7]:
import numpy as np
df_result['Weighted Average'] = (df_result['Mathematics'] * 0.4) +(df_result['Science'] * 0.2) + (df_result['English'] * 0.2) +(df_result['IT'] * 0.2)
df_result

  Student_ID  Mathematics  Science  English  IT  Average  Weighted Average
0       S001           85       78       90  89    85.50              85.4
1       S002           75       88       85  65    78.25              77.6
2       S003           95       82       80  88    86.25              88.0
3       S004           65       85       70  92    78.00              75.4
4       S005           90       79       95  98    90.50              90.4

In [11]:
import numpy as np
# Standardization function
def standardize(column):
 mean = np.mean(column)
 std_dev = np.std(column)
 return (column - mean) / std_dev
# Standardize the columns
df_result['Math_Std'] = standardize(df_result['Mathematics']).round(2)
df_result['Sci_Std'] = standardize(df_result['Science']).round(2)
df_result['Eng_Std'] = standardize(df_result['English']).round(2)
df_result['IT_Std'] = standardize(df_result['IT']).round(2)
df_result

,Student_ID,Mathematics,Science,English,IT,Average,Weighted Average,Math_Std,Sci_Std,Eng_Std,IT_Std
0,S001,85,78,90,89,85.50,85.4,0.28,-1.18,0.70,0.23
1,S002,75,88,85,65,78.25,77.6,-0.65,1.51,0.12,-1.90
2,S003,95,82,80,88,86.25,88.0,1.21,-0.11,-0.46,0.14
3,S004,65,85,70,92,78.00,75.4,-1.58,0.70,-1.63,0.50
4,S005,90,79,95,98,90.50,90.4,0.74,-0.91,1.28,1.03

In [14]:
import numpy as np
# Define a function to assign a grade based on the weighted average
def assign_grade(weighted_avg):
    if weighted_avg >= 85:
        return 'A'
    elif weighted_avg >= 75:
        return 'B'
    elif weighted_avg >= 65:
        return 'C'
    elif weighted_avg >= 55:
        return 'D'
    else:
        return 'F'
# Apply the grading function to the weighted averages
df_result['Final_Grade'] = np.array([assign_grade(avg) for avg in df_result['Weighted Average']])
df_result

,Student_ID,Mathematics,Science,English,IT,Average,Weighted Average,Math_Std,Sci_Std,Eng_Std,IT_Std,Final_Grade
0,S001,85,78,90,89,85.50,85.4,0.28,-1.18,0.70,0.23,A
1,S002,75,88,85,65,78.25,77.6,-0.65,1.51,0.12,-1.90,B
2,S003,95,82,80,88,86.25,88.0,1.21,-0.11,-0.46,0.14,A
3,S004,65,85,70,92,78.00,75.4,-1.58,0.70,-1.63,0.50,B
4,S005,90,79,95,98,90.50,90.4,0.74,-0.91,1.28,1.03,A